import Head from "next/head";
import { useState } from "react";
import Header from "~/components/Header";
import { api } from "~/utils/api";

export default function Home() {
  const [student, setStudent] = useState({
    name: "",
    email: "",
  });
  const { data: houseUnits, refetch: refetchHouseUnits } =
    api.houseUnits.getAll.useQuery();

  const createStudent = api.students.create.useMutation({
    onSuccess: () => {
      refetchHouseUnits();
    },
  });

  const addHouseUnitInterest = api.houseUnits.updateInterest.useMutation({
    onSuccess: () => {
      refetchHouseUnits();
    },
  });

  async function handleSubmit(e: any, id: string) {
    e.preventDefault();
    setStudent({ ...student });

    createStudent.mutate(student);
    addHouseUnitInterest.mutate({ id });
    await refetchHouseUnits();
    setStudent({ name: "", email: "" });
  }

  return (
    <>
      <Head>
        <title>Housing Cloud</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        {houseUnits?.map((unit) => (
          <>{unit.name}</>
        ))}
      </main>
    </>
  );
}
