import { ClipboardText, MagnifyingGlass } from "@phosphor-icons/react";
import Head from "next/head";
import { useState } from "react";
import { Modal } from "~/Modal";
import { Card } from "~/components/Card";
import { Form } from "~/components/Form";
import Header from "~/components/Header";
import { api } from "~/utils/api";

export default function Home() {
  const [modalOpen, setModalOpen] = useState(false);
  const [modalDetailsOpen, setModalDetailsOpen] = useState(false);
  const [houseUnit, setHouseUnit] = useState<any>();
  const { data: houseUnits, refetch: refetchHouseUnits } =
    api.houseUnits.getAll.useQuery();

  const createStudent = api.students.create.useMutation({
    onSuccess: () => {
      refetchHouseUnits();
    },
  });

  const addHouseUnitInterest = api.houseUnits.updateInterest.useMutation({
    onSuccess: () => {
      refetchHouseUnits();
    },
  });

  async function handleSubmit(e: any) {
    e.preventDefault();
    createStudent.mutate({
      name: e.target.name.value,
      email: e.target.email.value,
    });
    addHouseUnitInterest.mutate({ id: houseUnit!.id });
    await refetchHouseUnits();
  }

  function onOpenModal(houseUnit: any) {
    setModalOpen(true);
    setHouseUnit(houseUnit);
  }

  function onOpenDetailsModal(houseUnit: any) {
    setModalDetailsOpen(true);
    setHouseUnit(houseUnit);
  }

  const deletePost = api.houseUnits.delete.useMutation({
    onSuccess: () => {
      refetchHouseUnits();
    },
  });

  async function handleDelete(id: string) {
    deletePost.mutate({ id });
  }

  return (
    <>
      <Head>
        <title>Housing Cloud</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="mx-20 mb-1 grid gap-12 p-12 sm:grid-cols-2">
        {modalOpen && (
          <Form onModalOpen={setModalOpen} onSubmit={handleSubmit} />
        )}
        {modalDetailsOpen && (
          <Modal onModalOpen={setModalDetailsOpen} houseUnit={houseUnit} />
        )}
        {houseUnits?.map((house) => (
          <div>
            <Card unit={house} />
            <div className="-mt-5 flex gap-4">
              <button
                className="font-mono rounded-md bg-purple-300 p-2 text-purple-700 transition duration-0 hover:bg-purple-500 hover:text-purple-900 hover:duration-500"
                onClick={() => onOpenDetailsModal(house)}
              >
                <div className="mx-3 flex items-center justify-center gap-2">
                  <MagnifyingGlass size={24} />
                  <div className="text-md font-semibold">See details</div>
                </div>
              </button>

              <button
                className="font-mono rounded-md bg-purple-300 p-2 text-purple-700 transition duration-0 hover:bg-purple-500 hover:text-purple-900 hover:duration-500"
                onClick={() => onOpenModal(house)}
              >
                <div className="mx-3 flex items-center justify-center gap-2">
                  <ClipboardText size={24} />
                  <div className="text-md font-semibold">Apply</div>
                </div>
              </button>
            </div>
          </div>
        ))}
      </main>
    </>
  );
}
